In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1066, 6959, 2814, 5717],
 [1066, 6959, 2814, 2161],
 [1066, 7688, 2814, 6326],
 [6856, 6806, 4371, 5094, 6729],
 [6856, 6806, 4371, 5094, 4612],
 [17, 1066, 6970, 2814, 714],
 [7973, 3938, 7666, 5094]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1066 6959 2814 5717]
 [   0    0    0    0 1066 6959 2814 2161]
 [   0    0    0    0 1066 7688 2814 6326]
 [   0    0    0 6856 6806 4371 5094 6729]
 [   0    0    0 6856 6806 4371 5094 4612]
 [   0    0    0   17 1066 6970 2814  714]
 [   0    0    0    0 7973 3938 7666 5094]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 79ms/step


array([[[ 0.02447018,  0.02513976,  0.03210021,  0.03494013,
          0.04966234,  0.01666201, -0.00828284, -0.03777977,
         -0.02668434,  0.01745075],
        [ 0.02447018,  0.02513976,  0.03210021,  0.03494013,
          0.04966234,  0.01666201, -0.00828284, -0.03777977,
         -0.02668434,  0.01745075],
        [ 0.02447018,  0.02513976,  0.03210021,  0.03494013,
          0.04966234,  0.01666201, -0.00828284, -0.03777977,
         -0.02668434,  0.01745075],
        [ 0.02447018,  0.02513976,  0.03210021,  0.03494013,
          0.04966234,  0.01666201, -0.00828284, -0.03777977,
         -0.02668434,  0.01745075],
        [ 0.04831848, -0.02800431, -0.01401645, -0.03911262,
          0.02369538, -0.02231601, -0.00162605, -0.04022362,
          0.01243452,  0.02298209],
        [ 0.02911196, -0.01771201, -0.02351925, -0.01396128,
          0.03635   , -0.01885753, -0.02919742, -0.038852  ,
          0.00981021, -0.00203634],
        [-0.02243996, -0.03478352,  0.02479914, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 1066, 6959, 2814, 5717])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 35ms/step


array([[ 0.02447018,  0.02513976,  0.03210021,  0.03494013,  0.04966234,
         0.01666201, -0.00828284, -0.03777977, -0.02668434,  0.01745075],
       [ 0.02447018,  0.02513976,  0.03210021,  0.03494013,  0.04966234,
         0.01666201, -0.00828284, -0.03777977, -0.02668434,  0.01745075],
       [ 0.02447018,  0.02513976,  0.03210021,  0.03494013,  0.04966234,
         0.01666201, -0.00828284, -0.03777977, -0.02668434,  0.01745075],
       [ 0.02447018,  0.02513976,  0.03210021,  0.03494013,  0.04966234,
         0.01666201, -0.00828284, -0.03777977, -0.02668434,  0.01745075],
       [ 0.04831848, -0.02800431, -0.01401645, -0.03911262,  0.02369538,
        -0.02231601, -0.00162605, -0.04022362,  0.01243452,  0.02298209],
       [ 0.02911196, -0.01771201, -0.02351925, -0.01396128,  0.03635   ,
        -0.01885753, -0.02919742, -0.038852  ,  0.00981021, -0.00203634],
       [-0.02243996, -0.03478352,  0.02479914, -0.00925647, -0.02143223,
        -0.02390356, -0.03938638,  0.0134255 